### ISSUE TITLE
Part1: Russian text is left not translated

### ISSUE THREAD

**Issue by mikkovedru** [evilmartians/evil_chat#2]
https://evilmartians.com/chronicles/evil-front-part-1
In the "Okay, how do I lint my JS?" section there is some text in Russian that should be translated.
![image](https://user-images.githubusercontent.com/2521942/61796627-6fdd1800-ae2e-11e9-98e4-00f6544118fc.png)

**Comment by progapandist** [comment]
Fixed, thanks for the heads-up! 🙏 We usually right our articles in English from scratch, this was mostly a note to self that escaped editing 🙈

**Comment by mikkovedru** [comment]
You are welcome! :-)
